# Generated by Django 2.1.3 on 2019-07-29 05:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import v1.apps.lead.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lead_id', models.SlugField(default=v1.apps.lead.models.get_unique_slug, max_length=140, unique=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('lead_hash', models.CharField(max_length=40)),
                ('status', models.CharField(choices=[('raw', 'Raw Lead'), ('callback', 'Lead For Callback'), ('prospect', 'Prospect Lead'), ('sale', 'Lead For Sale')], default='raw', max_length=30)),
                ('next_callback', models.DateTimeField()),
                ('comment', models.TextField()),
                ('assigned_to', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assigned_leads', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
