# Generated by Django 2.1.3 on 2019-07-29 06:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('lead', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Callback',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='LeadBusinessDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('busines_name', models.CharField(max_length=50)),
                ('salutation', models.CharField(choices=[('Mr.', 'Mr.'), ('Mrs.', 'Mrs.'), ('Miss', 'Miss'), ('Dr.', 'Dr.'), ('Ms.', 'Ms.'), ('Prof.', 'Prof.'), ('Rev.', 'Rev.')], max_length=30)),
                ('first_name', models.CharField(max_length=50)),
                ('middle_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('phone_number', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None)),
                ('email', models.EmailField(max_length=254)),
                ('building_name', models.CharField(max_length=100)),
                ('subb', models.CharField(max_length=100)),
                ('building_number', models.CharField(max_length=50)),
                ('street_name', models.CharField(max_length=100)),
                ('town', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('county', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='SupplyDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meter_type', models.CharField(max_length=100)),
                ('meter_type_code', models.CharField(max_length=100)),
                ('domestic_meter', models.CharField(max_length=100)),
                ('amr', models.BooleanField(default=True)),
                ('related_meter', models.BooleanField(default=False)),
                ('current_electricity_supplier', models.CharField(max_length=100)),
                ('contract_end_date', models.DateField()),
                ('meter_serial_number', models.CharField(max_length=100)),
                ('supply_number', models.CharField(max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='lead',
            name='next_callback',
        ),
        migrations.AddField(
            model_name='supplydetails',
            name='lead',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='lead.Lead'),
        ),
        migrations.AddField(
            model_name='leadbusinessdetails',
            name='lead',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='lead.Lead'),
        ),
        migrations.AddField(
            model_name='callback',
            name='lead',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='callbacks', to='lead.Lead'),
        ),
        migrations.AddField(
            model_name='callback',
            name='scheduled_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scheduled_callbacks', to=settings.AUTH_USER_MODEL),
        ),
    ]
