# Generated by Django 2.1.3 on 2019-07-29 06:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lead', '0002_auto_20190729_0622'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SupplyDetails',
            new_name='LeadSupplyDetails',
        ),
    ]
