# Generated by Django 2.1.3 on 2019-07-31 04:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lead', '0006_auto_20190731_0450'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leadbusinessdetails',
            name='lead',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='business_detail', to='lead.Lead'),
        ),
        migrations.AlterField(
            model_name='leadsupplydetails',
            name='lead',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='supply_detail', to='lead.Lead'),
        ),
    ]
