# Generated by Django 2.1.3 on 2019-08-05 02:36

from django.db import migrations, models
from v1.apps.lead.models import Status

class Migration(migrations.Migration):
    def forward(apps, schema_editor):
        STATUS_RAW = "raw"
        STATUS_CALLBACK = "callback"
        STATUS_PROSPECT = "prospect"
        STATUS_SALE = "sale"    
        STATUS_CHOICES = (
            (STATUS_RAW, 'Raw Lead'),
            (STATUS_CALLBACK, "Lead For Callback"),
            (STATUS_PROSPECT, "Prospect Lead"),
            (STATUS_SALE, "Lead For Sale"),
        )
        Status.objects.bulk_create([Status(key=key, display=value) for key, value in STATUS_CHOICES])
        
    dependencies = [
        ('lead', '0008_lead_created_by'),
    ]

    operations = [
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=100)),
                ('display', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='callback',
            name='is_dialed',
            field=models.BooleanField(default=False),
        ),
        migrations.RunPython(forward)
    ]
