# Generated by Django 2.1.3 on 2019-08-05 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lead', '0010_auto_20190805_1526'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lead',
            name='status',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
    ]
