# Generated by Django 2.1.3 on 2019-08-05 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lead', '0011_auto_20190805_1602'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lead',
            name='status',
            field=models.CharField(default='raw', max_length=40),
            preserve_default=False,
        ),
    ]
