# Generated by Django 2.1.3 on 2019-08-09 03:32

from django.db import migrations, models
import v1.apps.lead.models


class Migration(migrations.Migration):

    dependencies = [
        ('lead', '0012_auto_20190805_1602'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lead',
            name='lead_id',
        ),
        migrations.AlterField(
            model_name='lead',
            name='lead_hash',
            field=models.SlugField(default=v1.apps.lead.models.get_unique_slug, max_length=140, unique=True),
        ),
        migrations.AlterField(
            model_name='leadbusinessdetails',
            name='building_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
