# Generated by Django 2.1.3 on 2019-08-10 03:02

from django.db import migrations, models
import v1.apps.lead.models


class Migration(migrations.Migration):

    dependencies = [
        ('lead', '0014_auto_20190810_0302'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lead',
            name='lead_internal_hash',
            field=models.SlugField(default=v1.apps.lead.models.get_unique_internal_slug, max_length=140),
        ),
    ]
