# Generated by Django 2.1.3 on 2019-09-09 03:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lead', '0017_auto_20190909_0233'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='source',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
