# Generated by Django 2.1.3 on 2019-10-22 03:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('lead', '0018_lead_source'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lead',
            old_name='city',
            new_name='city_or_town',
        ),
        migrations.RemoveField(
            model_name='lead',
            name='building_name',
        ),
        migrations.RemoveField(
            model_name='lead',
            name='building_number',
        ),
        migrations.RemoveField(
            model_name='lead',
            name='lead_hash',
        ),
        migrations.RemoveField(
            model_name='lead',
            name='lead_internal_hash',
        ),
        migrations.RemoveField(
            model_name='lead',
            name='meter_type',
        ),
        migrations.RemoveField(
            model_name='lead',
            name='meter_type_code',
        ),
        migrations.RemoveField(
            model_name='lead',
            name='street_name',
        ),
        migrations.RemoveField(
            model_name='lead',
            name='subb',
        ),
        migrations.RemoveField(
            model_name='lead',
            name='town',
        ),
        migrations.AddField(
            model_name='lead',
            name='address_1',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='lead',
            name='address_2',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='lead',
            name='address_3',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='lead',
            name='address_4',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='lead',
            name='agent_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='lead',
            name='assigned_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='have_assigned_leads', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='lead',
            name='assigned_on',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True),
        ),
        migrations.AddField(
            model_name='lead',
            name='bilge_eac',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='lead',
            name='can_sell_water',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='lead',
            name='contract_duration',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='lead',
            name='initial_disposition_made',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='lead',
            name='is_locked',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='lead',
            name='new_disposition_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='lead',
            name='new_renewal_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='lead',
            name='postcode',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='lead',
            name='s_andr3_status',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='lead',
            name='utility_type',
            field=models.CharField(blank=True, choices=[('Mr.', 'Mr.'), ('Mrs.', 'Mrs.'), ('Miss', 'Miss'), ('Dr.', 'Dr.'), ('Ms.', 'Ms.'), ('Prof.', 'Prof.'), ('Rev.', 'Rev.')], max_length=30, null=True),
        ),
    ]
