# Generated by Django 2.1.3 on 2019-10-30 01:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lead', '0019_auto_20191022_0307'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lead',
            name='initial_disposition_made',
        ),
        migrations.AddField(
            model_name='lead',
            name='initial_disposition_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
