# Generated by Django 2.1.3 on 2019-11-06 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lead', '0020_auto_20191030_0101'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubmissionStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=100)),
                ('display', models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='lead',
            name='utility_type',
            field=models.CharField(blank=True, choices=[('gas', 'GAS'), ('electricity', 'Elecricity')], max_length=30, null=True),
        ),
    ]
