# Generated by Django 2.1.3 on 2019-11-07 03:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lead', '0021_auto_20191106_1132'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='submission_status',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
    ]
