# Generated by Django 2.1.3 on 2019-11-07 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lead', '0022_lead_submission_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lead',
            name='status',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='lead',
            name='submission_status',
            field=models.CharField(default='raw', max_length=40),
        ),
    ]
