# Generated by Django 2.1.3 on 2019-11-08 01:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lead', '0024_auto_20191107_0651'),
    ]

    operations = [
        migrations.AddField(
            model_name='prospectlead',
            name='comment',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='leadhistory',
            name='action',
            field=models.CharField(choices=[('created', 'Lead Created'), ('edit', 'Lead Edited'), ('status changed', 'Lead Status Changed'), ('lead assign changed', 'Lead Assign Changed'), ('lead callback scheduled', 'Lead Callback Scheduled'), ('deleted', 'Lead Deleted'), ('comment', 'Comment Added'), ('submission status changed', 'Submission Status Changed'), ('pr', 'PR Submitted'), ('ht', 'Hot Transfer')], max_length=30),
        ),
    ]
