# Generated by Django 2.1.3 on 2019-11-08 01:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lead', '0025_auto_20191108_0149'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prospectlead',
            name='comment',
            field=models.TextField(default='test'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='prospectlead',
            name='status',
            field=models.CharField(choices=[('pr', 'Prospect'), ('unapproved', 'Unapproved'), ('hold', 'On Hold')], default='pr', max_length=30),
        ),
    ]
