# Generated by Django 2.1.3 on 2019-11-08 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lead', '0027_auto_20191108_0401'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leadhistory',
            name='action',
            field=models.CharField(choices=[('created', 'Lead Created'), ('edit', 'Lead Edited'), ('status changed', 'Lead Status Changed'), ('lead assign changed', 'Lead Assign Changed'), ('lead callback scheduled', 'Lead Callback Scheduled'), ('deleted', 'Lead Deleted'), ('comment', 'Comment Added'), ('submission status changed', 'Submission Status Changed'), ('pr', 'PR Submitted'), ('ht', 'Hot Transfer'), ('sale', 'Sale')], max_length=30),
        ),
        migrations.AlterField(
            model_name='leadsale',
            name='company_type',
            field=models.CharField(blank=True, choices=[('limited', 'Limited'), ('sole-trader', 'Sole Trader'), ('Partnership', 'Partnership')], max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='leadsale',
            name='full_address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='leadsale',
            name='full_billing_address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='leadsale',
            name='new_supplier',
            field=models.CharField(blank=True, choices=[('"Affect Energy"', '"Affect Energy"'), ('"Avanti Gas"', '"Avanti Gas"'), ('"Axis Energy"', '"Axis Energy"'), ('"BES Utilities"', '"BES Utilities"'), ('"Better Energy"', '"Better Energy"'), ('"BristolEnergy"', '"BristolEnergy"'), ('"British Gas"', '"British Gas"'), ('"Bulb"', '"Bulb"'), ('"Clear Business Energy"', '"Clear Business Energy"'), ('"Contract Natural Gas"', '"Contract Natural Gas"'), ('"Corona Energy"', '"Corona Energy"'), ('"Crown Gas and Power"', '"Crown Gas and Power"'), ('"daligas"', '"daligas"'), ('"Dong Energy"', '"Dong Energy"'), ('"E.On"', '"E.On"'), ('"Ecotricity"', '"Ecotricity"'), ('"EDF"', '"EDF"'), ('"Energia"', '"Energia"'), ('"Engie (Formerly GDF Suez)"', '"Engie (Formerly GDF Suez)"'), ('"Extra Energy"', '"Extra Energy"'), ('"F & S Energy"', '"F & S Energy"'), ('"Flogas"', '"Flogas"'), ('"Gazprom Energy"', '"Gazprom Energy"'), ('"GnERGY"', '"GnERGY"'), ('"Go Effortless Energy"', '"Go Effortless Energy"'), ('"Good Energy"', '"Good Energy"'), ('"Haven Power"', '"Haven Power"'), ('"Hudson Energy"', '"Hudson Energy"'), ('"LoCO2 Energy"', '"LoCO2 Energy"'), ('"MA Energy"', '"MA Energy"'), ('"Npower"', '"Npower"'), ('"Opus Energy"', '"Opus Energy"'), ('"OVO Energy"', '"OVO Energy"'), ('"Power NI"', '"Power NI"'), ('"Regent Gas"', '"Regent Gas"'), ('"Robin Hood Energy"', '"Robin Hood Energy"'), ('"ScottishPower"', '"ScottishPower"'), ('"Simple Gas"', '"Simple Gas"'), ('"Smartest Energy"', '"Smartest Energy"'), ('"SSE"', '"SSE"'), ('"Total Gas & Power"', '"Total Gas & Power"'), ('"United Gas and Power (UGP)"', '"United Gas and Power (UGP)"'), ('"Utilita Energy"', '"Utilita Energy"'), ('"Utility Warehouse"', '"Utility Warehouse"'), ('"Vattenfall"', '"Vattenfall"'), ('"Vayu Energy"', '"Vayu Energy"'), ('"Yorkshire Gas and Power (YGP)"', '"Yorkshire Gas and Power (YGP)"'), ('"Yu Energy"', '"Yu Energy"')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='leadsale',
            name='sold_as',
            field=models.CharField(blank=True, choices=[('utilities expert', 'Utilities Expert'), ('mv utilities', 'MV Utilities')], max_length=30, null=True),
        ),
    ]
