# Generated by Django 2.1.3 on 2019-11-08 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lead', '0028_auto_20191108_0942'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leadsale',
            name='renewal_acquisition',
            field=models.CharField(blank=True, choices=[('Acquisition', 'ACQUISITION'), ('Renewal', 'Renewal')], max_length=30, null=True),
        ),
    ]
