# Generated by Django 2.1.3 on 2019-11-09 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lead', '0029_auto_20191108_0942'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prospectlead',
            name='status',
        ),
        migrations.AddField(
            model_name='leadsale',
            name='management_status',
            field=models.CharField(blank=True, choices=[('submitted-to-supplier', 'Submitted To Supplier')], max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='leadsale',
            name='quality_status',
            field=models.CharField(choices=[('approved', 'Approved'), ('Reject', 'Rejected'), ('hold', 'On Hold'), ('audit', 'Require Auditing')], default='audit', max_length=30),
        ),
        migrations.AddField(
            model_name='prospectlead',
            name='quality_status',
            field=models.CharField(choices=[('approved', 'Approved'), ('Reject', 'Rejected'), ('hold', 'On Hold'), ('audit', 'Require Auditing')], default='audit', max_length=30),
        ),
        migrations.AlterField(
            model_name='leadsale',
            name='new_supplier',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
