# Generated by Django 2.1.3 on 2019-11-09 06:06

import datetime
from django.db import migrations, models
import django.utils.timezone
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('lead', '0030_auto_20191109_0551'),
    ]

    operations = [
        migrations.AddField(
            model_name='leadsale',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2019, 11, 9, 6, 6, 3, 905007, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='leadhistory',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
