# Generated by Django 2.1.3 on 2019-11-10 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lead', '0031_auto_20191109_0606'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leadsale',
            name='quality_status',
            field=models.CharField(choices=[('approved', 'Approved'), ('rejected', 'Rejected'), ('on-hold', 'On Hold'), ('audit', 'Require Auditing')], default='audit', max_length=30),
        ),
    ]
