# Generated by Django 2.1.3 on 2019-11-11 03:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lead', '0033_auto_20191110_0728'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leadsale',
            name='lead',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='sale', to='lead.Lead'),
            preserve_default=False,
        ),
    ]
