# Generated by Django 2.1.3 on 2019-11-11 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lead', '0034_auto_20191111_0327'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lead',
            name='supply_number',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
