# Generated by Django 2.1.3 on 2019-11-12 03:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lead', '0036_auto_20191111_1426'),
    ]

    operations = [
        migrations.AddField(
            model_name='leadsale',
            name='campaign',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
