# Generated by Django 2.1.3 on 2019-11-15 02:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('lead', '0037_leadsale_campaign'),
    ]

    operations = [
        migrations.AddField(
            model_name='prospectlead',
            name='quality_analyst',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prospects', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='prospectlead',
            name='quality_updated_on',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
