# Generated by Django 2.1.3 on 2019-11-16 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lead', '0038_auto_20191115_0233'),
    ]

    operations = [
        migrations.AddField(
            model_name='leadsale',
            name='quality_comment',
            field=models.CharField(blank=True, max_length=400, null=True),
        ),
        migrations.AddField(
            model_name='prospectlead',
            name='quality_comment',
            field=models.CharField(blank=True, max_length=400, null=True),
        ),
        migrations.AlterField(
            model_name='leadsale',
            name='comment',
            field=models.CharField(blank=True, max_length=400, null=True),
        ),
    ]
