# Generated by Django 2.1.3 on 2019-11-18 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lead', '0039_auto_20191116_0943'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prospectlead',
            name='quality_status',
            field=models.CharField(choices=[('approved', 'Approved'), ('rejected', 'Rejected'), ('on-hold', 'On Hold'), ('audit', 'Require Auditing')], default='audit', max_length=30),
        ),
    ]
