# Generated by Django 2.1.3 on 2019-11-20 03:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lead', '0040_auto_20191118_1002'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lead',
            name='can_sell_water',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
