# Generated by Django 2.1.3 on 2020-02-24 09:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('utils', '0005_businessnames'),
        ('lead', '0041_auto_20191120_0319'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='current_electricity_supplier_new',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='leads', to='utils.BusinessNames'),
        ),
        migrations.AddField(
            model_name='leadsale',
            name='new_supplier_new',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sales_new_supplier', to='utils.BusinessNames'),
        ),
    ]
