# Generated by Django 2.1.3 on 2019-09-12 04:52

from django.db import migrations, models
from v1.apps.utils.models import Settings

class Migration(migrations.Migration):
    def forward(apps, schema_editor):
        Settings.objects.create()

    dependencies = [
        ('utils', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Settings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_ip_restriction_active', models.BooleanField(default=False)),
            ],
        ),
        migrations.RunPython(forward, None)                                                                                           
    ]
