# Generated by Django 2.1.3 on 2020-02-24 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utils', '0004_auto_20191108_0348'),
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessNames',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
    ]
