# Generated by Django 2.1.3 on 2020-02-24 09:11

# Generated by Django 2.1.3 on 2020-02-24 09:03
import django
import json
from django.db import migrations

def forward(apps, schema_editor):
    BusinessNames = apps.get_model("utils", "BusinessNames")
    Settings = apps.get_model("utils", "Settings")
    Lead = apps.get_model("lead", "Lead")
    LeadSale = apps.get_model("lead", "LeadSale")
    supplier_names = Settings.objects.last().supplier_names
    supplier_names.sort()
    supplier_names = set([json.loads(n) for n in supplier_names])
    
    BusinessNames.objects.bulk_create([BusinessNames(name=name) for name in supplier_names])
    for l in Lead.objects.all():
        try:
            l.current_electricity_supplier_new = BusinessNames.objects.get(name=l.current_electricity_supplier)
            l.save()
        except:
            pass
    for l in LeadSale.objects.all():
        try:
            l.new_supplier_new = BusinessNames.objects.get(name=l.new_supplier)
            l.save()
        except:
            pass
        
class Migration(migrations.Migration):
    
    dependencies = [
                ('utils', '0005_businessnames'),
    ]

    operations = [
        migrations.RunPython(forward, django.db.migrations.operations.special.RunPython.noop)
    ]
