# Generated by Django 2.1.3 on 2019-07-29 03:32

from django.db import migrations
from django.contrib.auth.models import Group

class Migration(migrations.Migration):
    def forward(apps, schema_editor):
        Group.objects.bulk_create([
            Group(name='sales-person'),
            Group(name='team-manager'),
            Group(name='company-head'),
            Group(name='admin'),
        ])
        
    def reverse(apps, schema_editor):
        Group.objects.all().delete()

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(forward, reverse)
    ]
