# Generated by Django 2.1.3 on 2019-08-02 02:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_user_parentid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='parentId',
            new_name='parent',
        ),
    ]
