# Generated by Django 2.1.3 on 2019-09-11 03:01

from django.db import migrations
from django.contrib.auth.models import Group

class Migration(migrations.Migration):
    def forward(apps, schema_editor):
        Group.objects.bulk_create([
            Group(name='stage-1')])
        
    def reverse(apps, schema_editor):
        Group.objects.filter(name='stage-1').delete()

    dependencies = [
        ('accounts', '0007_auto_20190802_0246'),
    ]

    operations = [
        migrations.RunPython(forward, reverse)
    ]
    
