# Generated by Django 2.1.3 on 2020-02-24 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_user_has_ip_restriction'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='view_raw_leads',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='has_ip_restriction',
            field=models.BooleanField(default=False),
        ),
    ]
