# Generated by Django 2.1.3 on 2020-02-24 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_auto_20200224_0833'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='advance_search_enable',
            field=models.BooleanField(default=True),
        ),
    ]
